# @name test
GET http://localhost:3333/test

###

# @name get_all_memories
GET http://localhost:3333/memories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTHVpcyBNdW5ob3oiLCJhdmF0YXJVcmwiOiJodHRwczovL2F2YXRhcnMuZ2l0aHVidXNlcmNvbnRlbnQuY29tL3UvMTIzOTczMzk4P3Y9NCIsInN1YiI6ImJiZTdjOGZjLWE2YjMtNDc5YS1hMTg3LWU1NDEzM2JiYTRjYiIsImlhdCI6MTY5NzA0MTQ1NywiZXhwIjoxNjk5NjMzNDU3fQ.3JZIor7yQm-kvV5BFHHRgFYvPoVleYYwUCyD7BzgQo0

###

# @name get_memory
GET http://localhost:3333/memories/0ec05448-577a-47da-b1b5-2bfc9c295970

###

# @name create_memory
POST http://localhost:3333/memories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTHVpcyBNdW5ob3oiLCJhdmF0YXJVcmwiOiJodHRwczovL2F2YXRhcnMuZ2l0aHVidXNlcmNvbnRlbnQuY29tL3UvMTIzOTczMzk4P3Y9NCIsInN1YiI6ImJiZTdjOGZjLWE2YjMtNDc5YS1hMTg3LWU1NDEzM2JiYTRjYiIsImlhdCI6MTY5NzA0MTQ1NywiZXhwIjoxNjk5NjMzNDU3fQ.3JZIor7yQm-kvV5BFHHRgFYvPoVleYYwUCyD7BzgQo0

{
    "content": "Teste",
    "coverUrl": "Este é um teste",
    "isPublic": 0
}

###

# @name update_memory
PUT http://localhost:3333/memories/0ec05448-577a-47da-b1b5-2bfc9c295970
Content-Type: application/json

{
    "content": "Agora sou uma memória real",
    "coverUrl": "uau",
    "isPublic": 1
}

###

# @name delete_memory
DELETE  http://localhost:3333/memories/0ec05448-577a-47da-b1b5-2bfc9c295970

###

POST http://localhost:3333/register
Content-Type: application/json

{
    "code": "a6909e58d5f71e8d348f"
}

###

POST http://localhost:3333/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="background1.png"
Content-Type: image/png

< ./background1.png
------WebKitFormBoundary7MA4YWxkTrZu0gW-- 
